<script setup lang="ts">
import {ref} from 'vue'
import {mediaUrl} from './mediaUrl'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
const props=defineProps<{page:any;travel:any;offers:any[]}>()
const preview=ref<any>(null),open=ref(false),failed=ref<Record<string,boolean>>({})
function media(uuid:string){return props.page.images?.find((m:any)=>m.uuid===uuid)}
function reference(section:any){const list=section.reference_type==='trip'?props.travel.trips:section.reference_type==='destination'?props.travel.destinations:props.offers;return list?.find((r:any)=>r.uuid===section.reference_uuid)}
function referencePath(section:any){return '/'+({trip:'trips',destination:'destinations',rental_offer:'rental_offers'} as Record<string,string>)[section.reference_type]+'/'+section.reference_uuid+'/details'}
function show(m:any){preview.value=m;open.value=true}
</script>
<template>
<div class="space-y-5">
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground">
<div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="break-words text-xl font-semibold">{{page.title}}</h3><p v-if="page.sub_title" class="mt-1 break-words text-muted-foreground">{{page.sub_title}}</p></div><span class="rounded border px-3 py-1 text-sm">{{page.is_published?'Published':'Draft'}}</span></div>
<dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-muted-foreground">Page name</dt><dd class="break-words">{{page.name}}</dd></div><div><dt class="text-sm text-muted-foreground">Display order</dt><dd>{{page.sort_order??0}}</dd></div></dl>
<p class="whitespace-pre-wrap break-words text-sm">{{page.description||'No description provided.'}}</p>
</section>
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Page sections</h3><p v-if="!page.sections?.length" class="text-sm text-muted-foreground">No sections configured.</p>
<article v-for="(section,i) in page.sections" :key="section.key || i" class="space-y-3 rounded-lg border p-4"><p class="text-xs capitalize text-muted-foreground">Section {{Number(i)+1}} · {{section.type}}</p><h4 v-if="section.title" class="break-words font-semibold">{{section.title}}</h4><p v-if="section.value" class="break-words text-lg font-semibold">{{section.value}}</p><p v-if="section.text" class="whitespace-pre-wrap break-words text-sm">{{section.text}}</p>
<button v-if="media(section.media_uuid)" type="button" class="block w-full rounded border p-2" :aria-label="'View section image '+(section.title || Number(i)+1)" @click="show(media(section.media_uuid))"><img :src="mediaUrl(media(section.media_uuid).url)" :alt="media(section.media_uuid).title || section.title || 'Section image'" class="max-h-64 w-full object-contain"/></button>
<p v-if="section.cta_label || section.cta_url" class="break-words text-sm"><span class="text-muted-foreground">Button / link:</span> {{section.cta_label}} <span v-if="section.cta_url">({{section.cta_url}})</span></p>
<p v-if="section.reference_uuid" class="text-sm"><span class="text-muted-foreground">Featured content: </span><RouterLink v-if="reference(section)" :to="referencePath(section)" class="text-primary underline">{{reference(section).name || reference(section).title}}</RouterLink><span v-else>Referenced content is unavailable.</span></p>
<details v-if="Object.keys(section.translations||{}).length"><summary class="cursor-pointer text-sm">Section translations</summary><dl v-for="(fields,locale) in section.translations" :key="locale" class="mt-3 space-y-1 text-sm"><dt class="font-medium uppercase">{{locale}}</dt><dd v-for="(value,key) in fields" :key="key" class="whitespace-pre-wrap break-words"><span class="text-muted-foreground">{{String(key).replaceAll('_',' ')}}:</span> {{value}}</dd></dl></details>
</article></section>
<section class="space-y-3 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Photos and media</h3><p v-if="!page.images?.length" class="text-sm text-muted-foreground">No media uploaded. Use Edit page to add photos.</p><div v-else class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><button v-for="m in page.images" :key="m.uuid" type="button" class="min-w-0 overflow-hidden rounded-lg border text-left" :aria-label="'View photo '+(m.title || m.role || 'image')" @click="show(m)"><div class="aspect-[4/3] bg-muted/40"><p v-if="failed[m.url]" class="p-4 text-sm">Image unavailable</p><video v-else-if="m.role==='video'" :src="mediaUrl(m.url)" preload="metadata" class="h-full w-full object-contain"/><img v-else :src="mediaUrl(m.url)" :alt="m.title || page.title" loading="lazy" class="h-full w-full object-contain p-2" @error="failed[m.url]=true"/></div><p class="truncate p-3 text-sm">{{m.title || m.role || page.title}}</p></button></div></section>
<section class="space-y-3 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Search engine details</h3><dl class="space-y-3 text-sm"><div><dt class="text-muted-foreground">SEO title</dt><dd class="break-words">{{page.seo?.title || 'Not specified'}}</dd></div><div><dt class="text-muted-foreground">SEO description</dt><dd class="whitespace-pre-wrap break-words">{{page.seo?.description || 'Not specified'}}</dd></div></dl></section>
<details v-if="Object.keys(page.translations||{}).length" class="rounded-xl border bg-card p-5"><summary class="cursor-pointer font-semibold">Translations</summary><dl v-for="(fields,locale) in page.translations" :key="locale" class="mt-4 space-y-1 text-sm"><dt class="font-medium uppercase">{{locale}}</dt><dd v-for="(value,key) in fields" :key="key" class="whitespace-pre-wrap break-words"><span class="text-muted-foreground">{{String(key).replaceAll('_',' ')}}:</span> {{value}}</dd></dl></details>
<Dialog v-model:open="open"><DialogContent class="max-h-[90dvh] w-[calc(100vw_-_2rem)] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{{preview?.title || page.title}}</DialogTitle><DialogDescription>Page media preview</DialogDescription></DialogHeader><video v-if="preview?.role==='video'" :src="mediaUrl(preview.url)" controls class="max-h-[65vh] w-full"/><img v-else-if="preview && !failed[preview.url]" :src="mediaUrl(preview.url)" :alt="preview.title || page.title" class="max-h-[65vh] w-full object-contain" @error="failed[preview.url]=true"/><p v-else>Image unavailable.</p></DialogContent></Dialog>
</div>
</template>
