<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {onBeforeRouteLeave,useRoute,useRouter} from 'vue-router'
import MainLayout from '@/layouts/MainLayout.vue'
import Field from '@/components/services/ServiceField.vue'
import {Button} from '@/components/ui/button'
import {formError} from '@/components/services/formErrors'
import {enabled} from '@/components/workspace/listPresentation'
import api from '@/axiosClient'
const route=useRoute(),router=useRouter(),catalog=ref<any>(null),form=ref<any>(null),busy=ref(false),loading=ref(false),error=ref(''),notice=ref(''),dirty=ref(false),cover=ref<File|null>(null)
const currencyOptions=computed(()=>(catalog.value?.currencies||[]).map((c:any)=>({value:c.id,label:c.short_name})))
const selects=(list:any[],empty='Not specified')=>[{value:'',label:empty},...(list||[]).map(x=>({value:x.id,label:x.name}))]
function day(){return {uuid:null,day_number:(form.value?.days.length||0)+1,title:'',travel_date:'',destination_id:'',accommodation_id:'',accommodation_name:'',accommodation_notes:'',stay_type:'',nights:0,breakfast:false,lunch:false,dinner:false,description:'',activity_ids:[],activities:[]}}
function line(){return {description:'',traveler_type:'',source_type:'manual',source_id:null,quantity:1,unit_price:0,total_price:0,currency_id:form.value.currency_id,is_optional:false,is_visible:true}}
function term(){return {title:'',description:'',is_visible:true}}
const date=(v:any)=>v?String(v).slice(0,10):''
const flagKeys=['hide_price_breakdown','hide_total_price','hide_terms','hide_payment_terms','public_url_enabled','vat_enabled']
async function load(){loading.value=true;error.value='';form.value=null;try{catalog.value=(await api.get('/workspace/quotation-versions/'+route.params.id)).data;const v=catalog.value.version;
 form.value={...v,start_date:date(v.start_date),end_date:date(v.end_date),service_class_id:v.service_class_id||'',remove_cover_image:false,days:v.days.map((d:any)=>({...d,travel_date:date(d.travel_date),destination_id:d.destination_id||'',accommodation_id:d.accommodation_id||'',breakfast:enabled(d.breakfast),lunch:enabled(d.lunch),dinner:enabled(d.dinner),activity_ids:d.activities.map((a:any)=>a.activity_id).filter(Boolean)})),price_lines:v.price_lines.map((l:any)=>({...l,is_visible:enabled(l.is_visible),is_optional:enabled(l.is_optional)})),included_terms:v.terms.filter((t:any)=>t.type==='included'),excluded_terms:v.terms.filter((t:any)=>t.type==='excluded'),payment_terms:v.payment_terms};
 for(const key of flagKeys)form.value[key]=enabled(v[key]);
 // Retain selected catalog entries even if they have since been made inactive.
 for(const d of v.days){for(const [key,item]of [['destinations',d.destination],['accommodations',d.accommodation]] as const){if(item&&!catalog.value[key].some((x:any)=>x.id===item.id))catalog.value[key].push(item)}for(const a of d.activities){if(a.activity&&!catalog.value.activities.some((x:any)=>x.id===a.activity.id))catalog.value.activities.push(a.activity)}}
 dirty.value=false;cover.value=null;
 }catch(e){error.value=formError(e)}finally{loading.value=false}}
function reindex(){form.value.days.forEach((d:any,i:number)=>d.day_number=i+1);dirty.value=true}
function move(index:number,delta:number){const days=form.value.days;[days[index],days[index+delta]]=[days[index+delta],days[index]];reindex()}
function accommodation(d:any){const a=catalog.value.accommodations.find((a:any)=>String(a.id)===String(d.accommodation_id));if(a){d.accommodation_name=a.name;d.stay_type=a.stay_type?.name||''}dirty.value=true}
function recalculate(l:any){l.total_price=Number((Number(l.quantity||0)*Number(l.unit_price||0)).toFixed(2));dirty.value=true}
function addTerm(group:string,id:string){const a=[...catalog.value.includedAddons,...catalog.value.excludedAddons].find((a:any)=>String(a.id)===id);if(a)form.value[group].push({title:'',description:a.name,is_visible:true});dirty.value=true}
async function save(preview=false){busy.value=true;error.value='';notice.value='';try{const payload={...form.value};const body=new FormData();body.append('_method','PUT');body.append('payload',JSON.stringify(payload));if(cover.value)body.append('cover_image',cover.value);await api.post('/workspace/quotation-versions/'+route.params.id,body);dirty.value=false;if(preview){await router.push('/quotation-versions/'+route.params.id+'/preview')}else{await load();notice.value='Quotation saved. Totals were calculated by the existing pricing engine.'}}catch(e){error.value=formError(e)}finally{busy.value=false}}
watch(()=>route.params.id,load,{immediate:true})
onBeforeRouteLeave(()=>!dirty.value||window.confirm('Leave without saving your quotation changes?'))
</script>
<template><MainLayout title="Quotation builder"><div class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><RouterLink v-if="catalog?.version" :to="'/quotations/'+catalog.version.quotation.uuid+'/details'" class="text-sm underline">Back to quotation</RouterLink><h2 class="mt-2 text-xl font-semibold">{{catalog?.version.reference_number || 'Quotation builder'}}</h2><p class="text-sm text-muted-foreground">{{dirty?'Unsaved changes':'Edit this version in Dream Tour'}}</p></div><div v-if="form" class="flex gap-2"><Button :disabled="busy" @click="save(false)">{{busy?'Saving…':'Save quotation'}}</Button><Button variant="outline" :disabled="busy" @click="save(true)">Save &amp; preview</Button></div></div>
<p v-if="error" role="alert" class="rounded border border-destructive p-4 text-destructive">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><p v-if="loading" role="status">Loading builder…</p>
<form v-if="form" class="space-y-5" @submit.prevent="save(false)" @input="dirty=true" @change="dirty=true">
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Proposal details</h3><div class="grid gap-4 md:grid-cols-2"><Field v-model="form.title" label="Title" required/><Field v-model="form.subtitle" label="Subtitle"/><Field v-model="form.currency_id" label="Quote currency" type="select" :options="currencyOptions"/><Field v-model="form.service_class_id" label="Service class" type="select" :options="selects(catalog.serviceClasses)"/><Field v-model="form.start_date" label="Travel start" type="date"/><Field v-model="form.end_date" label="Travel end" type="date"/><Field v-model="form.guest_count" label="Guests" type="number" :min="1" required/></div><Field v-model="form.introduction" label="Introduction" type="textarea"/><Field v-model="form.highlights" label="Highlights (one per line)" type="textarea"/><Field v-model="form.agent_intro_letter" label="Agent introduction" type="textarea"/><Field v-model="form.company_profile" label="Company profile" type="textarea"/><Field v-model="form.internal_notes" label="Private staff notes" type="textarea"/><label class="block space-y-2 text-sm">Cover image (existing 5 MB limit)<input type="file" accept="image/*" class="block w-full rounded border p-2" @change="cover=($event.target as HTMLInputElement).files?.[0]||null"/></label><p v-if="form.cover_image_path" class="text-sm text-muted-foreground">This version has an existing cover image.</p><Field v-if="form.cover_image_path" v-model="form.remove_cover_image" label="Remove existing cover" type="checkbox"/></section>
<section class="space-y-4"><div class="flex items-center justify-between"><h3 class="text-lg font-semibold">Itinerary</h3><Button type="button" variant="outline" @click="form.days.push(day());dirty=true">Add day</Button></div><article v-for="(d,index) in form.days" :key="d.uuid || 'new-'+index" class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><div class="flex flex-wrap items-center justify-between gap-2"><h4 class="font-semibold">Day {{index+1}}</h4><div class="flex gap-2"><Button type="button" size="sm" variant="outline" :disabled="index===0" @click="move(index,-1)">Up</Button><Button type="button" size="sm" variant="outline" :disabled="index===form.days.length-1" @click="move(index,1)">Down</Button><Button type="button" size="sm" variant="outline" @click="form.days.splice(index,1);reindex()">Remove day</Button></div></div><div class="grid gap-4 md:grid-cols-2"><Field v-model="d.title" :label="'Day '+(index+1)+' title'"/><Field v-model="d.travel_date" label="Travel date" type="date"/><Field v-model="d.destination_id" label="Destination" type="select" :options="selects(catalog.destinations)"/><Field v-model="d.accommodation_id" label="Accommodation" type="select" :options="selects(catalog.accommodations)" @update:model-value="accommodation(d)"/><Field v-model="d.accommodation_name" label="Accommodation name / override"/><Field v-model="d.stay_type" label="Stay type"/><Field v-model="d.nights" label="Nights" type="number" :min="0"/></div><div class="flex flex-wrap gap-6"><Field v-model="d.breakfast" label="Breakfast" type="checkbox"/><Field v-model="d.lunch" label="Lunch" type="checkbox"/><Field v-model="d.dinner" label="Dinner" type="checkbox"/></div><Field v-model="d.description" label="Day description" type="textarea"/><Field v-model="d.accommodation_notes" label="Accommodation notes" type="textarea"/><label class="block text-sm font-medium">Activities<select v-model="d.activity_ids" multiple class="mt-1 block min-h-28 w-full rounded border bg-card p-2"><option v-for="a in catalog.activities" :key="a.id" :value="a.id">{{a.name}}</option></select></label><p v-if="d.activities?.some((a:any)=>!a.activity_id)" class="text-sm text-muted-foreground">Retained custom activities: {{d.activities.filter((a:any)=>!a.activity_id).map((a:any)=>a.title).join(', ')}}</p></article></section>
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><div class="flex items-center justify-between"><h3 class="font-semibold">Price lines</h3><Button type="button" variant="outline" @click="form.price_lines.push(line());dirty=true">Add price line</Button></div><p class="text-sm text-muted-foreground">Line totals may be adjusted explicitly, as in the existing builder. Quote totals and currency conversion are calculated on save.</p><article v-for="(l,index) in form.price_lines" :key="index" class="space-y-3 rounded border p-4"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field v-model="l.description" label="Line description" required/><Field v-model="l.traveler_type" label="Traveller / pricing tag"/><Field v-model="l.source_type" label="Source tag"/><Field v-model="l.quantity" label="Quantity" type="number" :min="1" @update:model-value="recalculate(l)"/><Field v-model="l.unit_price" label="Unit price" type="number" :min="0" step="0.01" @update:model-value="recalculate(l)"/><Field v-model="l.total_price" label="Line total" type="number" :min="0" step="0.01"/><Field v-model="l.currency_id" label="Line currency" type="select" :options="currencyOptions"/></div><div class="flex flex-wrap items-center gap-5"><Field v-model="l.is_optional" label="Optional" type="checkbox"/><Field v-model="l.is_visible" label="Visible to guest" type="checkbox"/><Button type="button" size="sm" variant="outline" @click="form.price_lines.splice(index,1);dirty=true">Remove line</Button></div></article><p class="text-sm">Last saved total: {{catalog.version.currency?.short_name}} {{Number(catalog.version.total_amount).toFixed(2)}}</p></section>
<section v-for="group in ['included_terms','excluded_terms','payment_terms']" :key="group" class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><div class="flex flex-wrap items-center justify-between gap-2"><h3 class="font-semibold">{{group.replaceAll('_',' ')}}</h3><Button type="button" variant="outline" @click="form[group].push(term());dirty=true">Add term</Button></div><label v-if="group!=='payment_terms'" class="block text-sm">Add from existing inclusions/exclusions<select class="mt-1 block w-full rounded border bg-card p-2" @change="addTerm(group,($event.target as HTMLSelectElement).value);($event.target as HTMLSelectElement).value='' "><option value="">Choose an existing item</option><option v-for="a in group==='included_terms'?catalog.includedAddons:catalog.excludedAddons" :key="a.id" :value="a.id">{{a.name}}</option></select></label><div v-for="(t,index) in form[group]" :key="index" class="space-y-3 rounded border p-3"><Field v-model="t.title" label="Term title"/><Field v-model="t.description" label="Term description" type="textarea" required/><div class="flex items-center gap-4"><Field v-model="t.is_visible" label="Visible" type="checkbox"/><Button type="button" size="sm" variant="outline" @click="form[group].splice(index,1);dirty=true">Remove term</Button></div></div></section>
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Display and sharing</h3><div class="grid gap-4 sm:grid-cols-2"><Field v-model="form.vat_enabled" label="Apply existing VAT rule" type="checkbox"/><Field v-model="form.hide_price_breakdown" label="Hide price breakdown" type="checkbox"/><Field v-model="form.hide_total_price" label="Hide total price" type="checkbox"/><Field v-model="form.hide_terms" label="Hide terms" type="checkbox"/><Field v-model="form.hide_payment_terms" label="Hide payment terms" type="checkbox"/><Field v-model="form.public_url_enabled" label="Enable guest link" type="checkbox"/></div></section><Button type="submit" :disabled="busy">{{busy?'Saving…':'Save quotation'}}</Button>
</form></div></MainLayout></template>
