<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import MainLayout from '@/layouts/MainLayout.vue'
import Field from '@/components/services/ServiceField.vue'
import {Button} from '@/components/ui/button'
import {formError} from '@/components/services/formErrors'
import api from '@/axiosClient'
const route=useRoute(),data=ref<any>(null),error=ref(''),notice=ref(''),busy=ref(''),documentVisible=ref(false),documentLoaded=ref(false),showBooking=ref(false),agreed=ref(false),booking=ref<any>({})
const version=computed(()=>data.value?.version)
const servicePath=computed(()=>version.value?.quotation?.inquiry?.service_details?'/inquiries/'+version.value.quotation.inquiry.uuid+'/services':'')
const documentUrl=computed(()=>api.getUri({url:'/quotation-versions/'+route.params.id+'/print-preview'}))
async function load(){error.value='';data.value=null;documentVisible.value=false;documentLoaded.value=false;try{data.value=(await api.get('/workspace/quotation-versions/'+route.params.id+'/preview')).data;const t=version.value.quotation.tourist||{};const [fname,...rest]=(t.name||'').split(' ');booking.value={fname,lname:rest.join(' '),email:t.email||'',phone:t.phone||'',country:t.country?.name||'',guest_count:version.value.guest_count,start_date:version.value.start_date?.slice(0,10)||'',note:''}}catch(e){error.value=formError(e)}}
async function action(name:string){busy.value=name;error.value='';notice.value='';try{const result=(await api.post('/workspace/quotation-versions/'+route.params.id+'/'+name)).data;if(result.share)data.value.share=result.share;notice.value=name==='pdf'?'PDF generated. You can download it below.':'Guest link enabled. Copy the link or message below.'}catch(e){error.value=formError(e)}finally{busy.value=''}}
async function download(){busy.value='download';error.value='';try{const response=await api.get('/quotation-versions/'+route.params.id+'/download-pdf',{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=(version.value.reference_number||'quotation').replace(/[^\w.-]/g,'_')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=formError(e)}finally{busy.value=''}}
async function copy(value:string){try{await navigator.clipboard.writeText(value);notice.value='Copied to clipboard'}catch{error.value='Copy failed. Select and copy the text below.'}}
async function book(){busy.value='book';error.value='';try{const result=(await api.post('/quotation-versions/'+route.params.id+'/book',booking.value)).data;if(!result.ok)throw Error(result.message||'Booking failed');notice.value='Booking recorded: '+(result.booking_reference||'');showBooking.value=false;await load()}catch(e){error.value=formError(e)}finally{busy.value=''}}
watch(()=>route.params.id,load,{immediate:true})
</script>
<template><MainLayout title="Quotation preview"><div class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><RouterLink v-if="version" :to="'/quotations/'+version.quotation.uuid+'/details'" class="text-sm underline">Back to quotation</RouterLink><h2 class="mt-2 text-xl font-semibold">{{version?.reference_number || 'Quotation preview'}}</h2></div><div v-if="version" class="flex flex-wrap gap-2"><RouterLink v-if="!servicePath" :to="'/quotation-versions/'+version.uuid+'/builder'"><Button variant="outline">Edit quotation</Button></RouterLink><Button :disabled="!!busy" @click="action('pdf')">{{busy==='pdf'?'Generating PDF…':'Generate PDF'}}</Button><Button variant="outline" :disabled="!!busy" @click="download">{{busy==='download'?'Preparing download…':'Download PDF'}}</Button><Button variant="outline" :disabled="!!busy" @click="action('share')">{{busy==='share'?'Preparing link…':'Create guest link'}}</Button></div></div>
<p v-if="error" role="alert" class="rounded border border-destructive p-4 text-destructive">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<template v-if="version"><section class="space-y-3 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">{{version.title}}</h3><p>{{version.currency?.short_name}} {{Number(version.total_amount).toFixed(2)}} · {{version.status}} · {{version.guest_count}} guests</p><p class="text-sm text-muted-foreground">PDF rendering and the document preview can take longer than opening the quotation details. Generating a PDF also enables the guest link, following the existing workflow.</p><Button v-if="!documentVisible" variant="outline" @click="documentVisible=true">Load document preview</Button><p v-if="documentVisible&&!documentLoaded" role="status">Loading document…</p><iframe v-if="documentVisible" :src="documentUrl" title="Quotation document preview" sandbox="allow-scripts" class="h-[75vh] min-h-96 w-full rounded border bg-white" @load="documentLoaded=true"/></section>
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Guest link and message drafts</h3><p class="text-sm text-muted-foreground">These are drafts to copy. No email or WhatsApp message is sent automatically.</p><div v-if="data.share.public_proposal_url" class="space-y-2"><p class="break-all text-sm">{{data.share.public_proposal_url}}</p><Button variant="outline" @click="copy(data.share.public_proposal_url)">Copy guest link</Button></div><p v-else class="text-sm">Guest access is disabled. Create a guest link when the proposal is ready.</p><details><summary class="cursor-pointer font-medium">Email draft</summary><p class="my-2 text-sm">{{data.share.email_subject}}</p><pre class="whitespace-pre-wrap break-words font-sans text-sm">{{data.share.email_body}}</pre><Button class="mt-3" variant="outline" @click="copy(data.share.email_subject+'\n\n'+data.share.email_body)">Copy email draft</Button></details><details><summary class="cursor-pointer font-medium">WhatsApp draft</summary><p class="my-2 whitespace-pre-wrap break-words text-sm">{{data.share.whatsapp_message}}</p><Button variant="outline" @click="copy(data.share.whatsapp_message)">Copy WhatsApp draft</Button></details></section>
<section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Booking</h3><RouterLink v-if="servicePath" :to="servicePath"><Button variant="outline">Manage supply and agreed service booking</Button></RouterLink><p v-else-if="version.booking_id">This version already has a booking. <RouterLink to="/bookings/list" class="underline">View bookings</RouterLink></p><template v-else><Button v-if="!showBooking" variant="outline" @click="showBooking=true">Record agreed booking</Button><form v-if="showBooking" class="space-y-4" @submit.prevent="book"><p class="text-sm text-muted-foreground">This uses the existing trip booking workflow.</p><div class="grid gap-4 md:grid-cols-2"><Field v-model="booking.fname" label="First name" required/><Field v-model="booking.lname" label="Last name"/><Field v-model="booking.email" label="Email" type="email" required/><Field v-model="booking.phone" label="Phone"/><Field v-model="booking.country" label="Country"/><Field v-model="booking.guest_count" label="Guests" type="number" :min="1"/><Field v-model="booking.start_date" label="Travel date" type="date"/></div><Field v-model="booking.note" label="Booking notes" type="textarea"/><Field v-model="agreed" label="The customer agreed to this quotation" type="checkbox"/><Button type="submit" :disabled="!!busy||!agreed">{{busy==='book'?'Recording booking…':'Confirm agreed booking'}}</Button></form></template></section>
</template><p v-else-if="!error" role="status">Loading preview controls…</p></div></MainLayout></template>
