<script setup lang="ts">
import {ref,onMounted,computed,watch} from 'vue'
import {useRoute} from 'vue-router'
import RentalOfferDetails from '@/components/services/RentalOfferDetails.vue'
import MainLayout from '@/layouts/MainLayout.vue'
import DataTableReport from '@/components/datatable/DataTableReport.vue'
import Field from '@/components/services/ServiceField.vue'
import LocalizedFields from '@/components/services/LocalizedFields.vue'
import LibraryMedia from '@/components/services/LibraryMedia.vue'
import {formError,options} from '@/components/services/formErrors'
import {Button} from '@/components/ui/button'
import api from '@/axiosClient'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
import {mediaUrl} from '@/components/services/mediaUrl'
const props=defineProps<{details?:boolean}>(),route=useRoute()
const rows=ref<any[]>([]),vehicles=ref<any[]>([]),types=ref<string[]>([]),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),tab=ref('offers')
const form=ref<any>(null),vehicle=ref<any>(null)
const selectedOffer=computed(()=>rows.value.find(row=>row.uuid===route.params.id))
watch(()=>[props.details,route.params.id],()=>{form.value=null;error.value='';notice.value='';tab.value='offers'})
const cover=(row:any)=>row.images?.find((m:any)=>m.role==='cover')||row.images?.find((m:any)=>m.role!=='video')
const columns=[{key:'photo',label:'Photo'},{key:'title',label:'Offer',sortable:true},{key:'purpose',label:'Purpose',sortable:true},{key:'vehicle_type',label:'Vehicle type'},{key:'is_published',label:'Published',formatter:(v:any)=>v?'Yes':'No'},{key:'actions',label:'Manage'}]
const vehicleOptions=computed(()=>[{value:'',label:'Select an existing vehicle'},...vehicles.value.map(v=>({value:v.uuid,label:v.name}))])
async function load(){loading.value=true;error.value='';try{const {data}=await api.get('/workspace/rental-offers');rows.value=data.data.rental_offers;vehicles.value=data.data.vehicles;types.value=data.data.vehicle_types;if(form.value?.uuid)form.value.images=rows.value.find(r=>r.uuid===form.value.uuid)?.images??[]}catch(e){error.value=formError(e)}finally{loading.value=false}}
function edit(row?:any){form.value={title:'',description:'',purpose:'private',vehicle_type:'sedan',vehicle_uuids:[],price_unit:'day',driver_policy:'included',fuel_policy:'excluded',is_active:true,is_published:false,is_featured:false,sort_order:0,translations:{},...JSON.parse(JSON.stringify(row??{})),details:{duration:'',inclusions:'',exclusions:'',terms:'',mileage:'',extras:[],service_locations:[],...JSON.parse(JSON.stringify(row?.details??{}))}};notice.value='';error.value=''}
async function save(){busy.value=true;error.value='';try{const url='/workspace/rental-offers'+(form.value.uuid?'/'+form.value.uuid:'');const {data}=await api.request({url,method:form.value.uuid?'PUT':'POST',data:form.value});edit(data.data.rental_offer);await load();notice.value='Rental offer saved'}catch(e){error.value=formError(e)}finally{busy.value=false}}
function selectVehicle(uuid:string){const v=vehicles.value.find(v=>v.uuid===uuid);vehicle.value=v?{...v,rental_specs:{vehicle_type:'sedan',make:'',model:'',seats:null,transmission:'automatic',fuel_type:'',features:[],luggage_capacity:'',service_locations:[],...(v.rental_specs??{})},translations:v.translations??{}}:null}
async function saveVehicle(){busy.value=true;error.value='';try{await api.put('/workspace/vehicles/'+vehicle.value.uuid+'/rental',vehicle.value);await load();notice.value='Vehicle specifications saved'}catch(e){error.value=formError(e)}finally{busy.value=false}}
function closeEditor(value:boolean){if(!value&&!busy.value){form.value=null;error.value='';notice.value=''}}
const lines=(value:string)=>(value??'').split('\n').map(s=>s.trim()).filter(Boolean)
onMounted(load)
</script>
<template><MainLayout :title="details ? 'Rental offer' : 'Car rental'"><div class="space-y-5">
<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">{{details ? 'Rental offer details' : 'Car rental'}}</h2><p class="text-sm text-muted-foreground">Quotation-only offers · Staff must verify availability</p></div><div class="flex flex-wrap gap-2"><RouterLink v-if="details" to="/rental_offers/list"><Button variant="outline">Back to rental offers</Button></RouterLink><Button v-if="details && selectedOffer" @click="edit(selectedOffer)">Edit rental offer</Button><RouterLink v-if="!details" to="/vehicles/list"><Button variant="outline">Existing vehicle catalog</Button></RouterLink></div></div>
<div v-if="!details" class="flex gap-2"><Button :variant="tab==='offers'?'default':'outline'" @click="tab='offers'">Rental offers</Button><Button :variant="tab==='vehicles'?'default':'outline'" @click="tab='vehicles'">Vehicle specifications</Button></div>
<p v-if="error && !form" role="alert" class="rounded border border-destructive p-3 text-destructive">{{error}}</p><p v-if="notice && !form" role="status">{{notice}}</p>
<template v-if="details"><p v-if="loading" role="status">Loading rental offer…</p><RentalOfferDetails v-else-if="selectedOffer" :key="selectedOffer.uuid" :offer="selectedOffer" :vehicles="vehicles"/><p v-else-if="!error" role="alert" class="rounded border p-5">Rental offer not found.</p></template>
<template v-if="tab==='offers'"><Button v-if="!details" @click="edit()">New rental offer</Button><DataTableReport v-if="!details" :columns="columns" :rows="rows" :loading="loading" :show-date-filter="false"><template #cell-photo="{row}"><img v-if="cover(row)" :src="mediaUrl(cover(row).url)" :alt="String(row.title || 'Rental offer')" class="h-14 w-20 rounded-md border bg-muted/30 object-contain"/><span v-else class="text-xs text-muted-foreground">No photo</span></template><template #cell-actions="{row}"><div class="flex gap-2"><RouterLink :to="'/rental_offers/'+row.uuid+'/details'"><Button variant="outline" size="sm">View</Button></RouterLink><Button variant="outline" size="sm" @click="edit(row)">Edit</Button></div></template></DataTableReport>
<Dialog :open="!!form" @update:open="closeEditor"><DialogContent class="max-h-[90dvh] w-[calc(100vw_-_2rem)] overflow-y-auto sm:max-w-4xl" @escape-key-down="busy && $event.preventDefault()" @interact-outside="busy && $event.preventDefault()">
<DialogHeader><DialogTitle>{{form?.uuid?'Edit rental offer':'New rental offer'}}</DialogTitle><DialogDescription>Enter the rental details, then save to add photos. Availability is confirmed by staff.</DialogDescription></DialogHeader>
<template v-if="form"><p v-if="error" role="alert" class="rounded border border-destructive p-3 text-sm text-destructive">{{error}}</p><p v-if="notice" role="status" class="text-sm">{{notice}}</p>
<form class="space-y-4" @submit.prevent="save"><fieldset class="min-w-0 space-y-4" :disabled="busy">
<div class="grid gap-4 sm:grid-cols-2"><Field v-model="form.title" label="Title" required/><Field v-model="form.purpose" label="Rental purpose" type="select" :options="options(['corporate','private','wedding','event'])"/><Field v-model="form.vehicle_type" label="Vehicle type" type="select" :options="options(types)"/><Field v-model="form.price_unit" label="Quotation price unit" type="select" :options="options(['day','hour','transfer','package'])"/><Field v-model="form.driver_policy" label="Driver" type="select" :options="options(['included','excluded','selectable'])"/><Field v-model="form.fuel_policy" label="Fuel" type="select" :options="options(['included','excluded','selectable'])"/><Field v-model="form.details.duration" label="Duration description"/><Field v-model="form.sort_order" label="Display order" type="number" :min="0"/></div>
<Field v-model="form.description" label="Description" type="textarea"/><div class="grid gap-4 sm:grid-cols-2"><Field v-for="field in ['inclusions','exclusions','terms','mileage']" :key="field" v-model="form.details[field]" :label="field==='mileage'?'Mileage and extra-distance terms':field" type="textarea"/></div>
<Field :model-value="form.details.service_locations.join('\n')" label="Service locations (one per line)" type="textarea" @update:model-value="form.details.service_locations=lines($event)"/>
<fieldset class="rounded border p-3"><legend class="px-1 text-sm font-medium">Eligible catalog vehicles (leave empty to use the vehicle type)</legend><div class="grid gap-2 sm:grid-cols-2"><label v-for="v in vehicles" :key="v.uuid" class="flex items-center gap-2 text-sm"><input v-model="form.vehicle_uuids" type="checkbox" :value="v.uuid" class="accent-primary"/>{{v.name}}</label></div></fieldset>
<section class="space-y-3 rounded border p-3"><h4 class="font-medium">Optional extras — priced by quotation</h4><div v-for="(extra,i) in form.details.extras" :key="extra.code" class="grid items-end gap-3 sm:grid-cols-[1fr_2fr_auto]"><Field v-model="extra.title" label="Extra name" required/><Field v-model="extra.description" label="Description"/><Button type="button" variant="outline" @click="form.details.extras.splice(i,1)">Remove</Button></div><Button type="button" variant="outline" @click="form.details.extras.push({code:'extra_'+Date.now(),title:'',description:''})">Add extra</Button></section>
<div class="flex flex-wrap gap-6"><Field v-model="form.is_active" label="Active" type="checkbox"/><Field v-model="form.is_published" label="Published" type="checkbox"/><Field v-model="form.is_featured" label="Featured" type="checkbox"/></div><LocalizedFields v-model="form.translations" :fields="['title','description']"/><Button type="submit" :disabled="busy">{{busy?'Saving…':'Save rental offer'}}</Button>
</fieldset></form><p v-if="!form.uuid" class="text-sm text-muted-foreground">Save the offer first. You can then upload and preview its photos here.</p>
<LibraryMedia v-else type="rental-offers" :uuid="form.uuid" :images="form.images??[]" :disabled="busy" @saved="load"/>
</template></DialogContent></Dialog></template>
<template v-else><div class="rounded-xl border bg-card p-5 text-card-foreground"><Field :model-value="vehicle?.uuid??''" label="Vehicle" type="select" :options="vehicleOptions" @update:model-value="selectVehicle($event)"/><form v-if="vehicle" class="mt-4 space-y-4" @submit.prevent="saveVehicle"><div class="grid gap-4 sm:grid-cols-2"><Field v-model="vehicle.rental_specs.vehicle_type" label="Vehicle type" type="select" :options="options(types)"/><Field v-model="vehicle.rental_specs.make" label="Make"/><Field v-model="vehicle.rental_specs.model" label="Model"/><Field v-model="vehicle.rental_specs.seats" label="Seats" type="number" :min="1" required/><Field v-model="vehicle.rental_specs.transmission" label="Transmission" type="select" :options="options(['automatic','manual'])"/><Field v-model="vehicle.rental_specs.fuel_type" label="Fuel type" required/><Field v-model="vehicle.rental_specs.luggage_capacity" label="Luggage capacity"/><Field v-model="vehicle.is_rental_published" label="Publish in rental catalog" type="checkbox"/></div><Field v-for="key in ['features','service_locations']" :key="key" :model-value="(vehicle.rental_specs[key]??[]).join('\n')" :label="key.replaceAll('_',' ')+' (one per line)'" type="textarea" @update:model-value="vehicle.rental_specs[key]=lines($event)"/><LocalizedFields v-model="vehicle.translations" :fields="['name','description']"/><Button type="submit" :disabled="busy">Save rental specifications</Button><RouterLink :to="'/vehicles/'+vehicle.uuid+'/details'" class="ml-3 text-sm underline">Vehicle details and images</RouterLink></form></div></template>
</div></MainLayout></template>
