<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import MainLayout from '@/layouts/MainLayout.vue'
import DataTableReport from '@/components/datatable/DataTableReport.vue'
import Field from '@/components/services/ServiceField.vue'
import LocalizedFields from '@/components/services/LocalizedFields.vue'
import LibraryMedia from '@/components/services/LibraryMedia.vue'
import {formError,options} from '@/components/services/formErrors'
import {Button} from '@/components/ui/button'
import api from '@/axiosClient'
import ContentPageDetails from '@/components/services/ContentPageDetails.vue'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
const route=useRoute(),rows=ref<any[]>([]),form=ref<any>(null),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),travel=ref<any>({trips:[],destinations:[]}),offers=ref<any[]>([])
const columns=[{key:'name',label:'Page',sortable:true},{key:'title',label:'Title'},{key:'is_published',label:'Published',formatter:(v:any)=>v?'Yes':'No'},{key:'sort_order',label:'Order',sortable:true},{key:'actions',label:'Manage'}]
const detailMode=computed(()=>Boolean(route.params.id)), page=computed(()=>rows.value.find(p=>p.uuid===route.params.id))
function closeEditor(open:boolean){if(!open&&!busy.value)form.value=null}
watch(()=>route.params.id,()=>{form.value=null;error.value='';notice.value=''})
const images=computed(()=>form.value?.images??[])
async function load(){loading.value=true;error.value='';try{const {data}=await api.get('/workspace/pages-content');rows.value=data.data.pages;if(form.value?.uuid)form.value.images=rows.value.find(p=>p.uuid===form.value.uuid)?.images??[]}catch(e){error.value=formError(e)}finally{loading.value=false}}
function edit(row?:any){error.value='';notice.value='';form.value={name:'',title:'',sub_title:'',description:'',is_published:false,sort_order:0,sections:[],translations:{},seo:{title:'',description:''},...JSON.parse(JSON.stringify(row??{}))};form.value.seo??={title:'',description:''};form.value.sections??=[]}
async function save(){busy.value=true;error.value='';try{const {data}=await api.request({url:'/workspace/pages-content'+(form.value.uuid?'/'+form.value.uuid:''),method:form.value.uuid?'PUT':'POST',data:form.value});edit(data.data.page);await load();notice.value='Page saved'}catch(e){error.value=formError(e)}finally{busy.value=false}}
function addSection(){form.value.sections.push({key:'section_'+Date.now(),type:'service',title:'',text:'',value:'',cta_label:'',cta_url:'',media_uuid:null,reference_type:null,reference_uuid:null,translations:{}})}
function move(i:number,dir:number){const a=form.value.sections;if(i+dir<0||i+dir>=a.length)return;[a[i],a[i+dir]]=[a[i+dir],a[i]]}
function referenceOptions(type:string){const items=type==='trip'?travel.value.trips:type==='destination'?travel.value.destinations:offers.value;return[{value:'',label:'No selection'},...items.map((i:any)=>({value:i.uuid,label:i.name??i.title}))]}
onMounted(async()=>{await load();try{const responses=await Promise.all([api.get('/workspace/travel-content'),api.get('/workspace/rental-offers')]);travel.value=responses[0].data.data;offers.value=responses[1].data.data.rental_offers}catch(e){error.value=formError(e)}})
</script>
<template><MainLayout title="Pages"><div class="space-y-5"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-semibold">Website pages</h2><p class="text-sm text-muted-foreground">Page content, sections, translations and images</p></div><div class="flex flex-wrap gap-2"><RouterLink to="/travel_content/list"><Button variant="outline">Travel content</Button></RouterLink><RouterLink v-if="detailMode" to="/pages/list"><Button variant="outline">Back to pages</Button></RouterLink><Button v-if="detailMode && page" @click="edit(page)">Edit page</Button><Button v-if="!detailMode" @click="edit()">New page</Button></div></div>
<p v-if="error" role="alert" class="rounded border border-destructive p-3 text-destructive">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><p v-if="detailMode && loading" role="status">Loading page…</p><ContentPageDetails v-else-if="detailMode && page" :page="page" :travel="travel" :offers="offers"/><p v-else-if="detailMode && !error" role="status">Page not found.</p><DataTableReport v-if="!detailMode" :rows="rows" :columns="columns" :loading="loading" :show-date-filter="false"><template #cell-actions="{row}"><div class="flex gap-2"><RouterLink :to="'/pages/'+row.uuid+'/details'"><Button variant="outline" size="sm">View</Button></RouterLink><Button variant="outline" size="sm" @click="edit(row)">Edit page</Button></div></template></DataTableReport>
<Dialog :open="Boolean(form)" @update:open="closeEditor"><DialogContent class="max-h-[90dvh] w-[calc(100vw_-_2rem)] overflow-y-auto sm:max-w-4xl" @escape-key-down="busy && $event.preventDefault()" @interact-outside="busy && $event.preventDefault()"><DialogHeader><DialogTitle>{{form?.uuid?'Edit page':'New page'}}</DialogTitle><DialogDescription>Manage website content, sections and photos.</DialogDescription></DialogHeader><p v-if="error" role="alert" class="text-destructive">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><form v-if="form" class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground" @submit.prevent="save"><fieldset :disabled="busy" class="min-w-0 space-y-4"><div class="grid gap-4 sm:grid-cols-2"><Field v-model="form.name" label="Page name (for example: business-travel)" required/><Field v-model="form.title" label="Title" required/><Field v-model="form.sub_title" label="Subtitle"/><Field v-model="form.sort_order" label="Display order" type="number" :min="0"/></div><Field v-model="form.description" label="Description" type="textarea" required/><div class="grid gap-4 sm:grid-cols-2"><Field v-model="form.seo.title" label="SEO title"/><Field v-model="form.seo.description" label="SEO description" type="textarea"/></div><LocalizedFields v-model="form.translations" :fields="['title','sub_title','description','seo_title','seo_description']"/>
<section class="space-y-4"><h3 class="font-semibold">Page sections</h3><div v-for="(section,i) in form.sections" :key="section.key" class="space-y-3 rounded-lg border p-4"><div class="flex flex-wrap items-center justify-between gap-2"><h4 class="font-medium">Section {{i+1}} · {{section.type}}</h4><div class="flex gap-2"><Button type="button" size="sm" variant="outline" :disabled="i===0" aria-label="Move section earlier" @click="move(i,-1)">↑</Button><Button type="button" size="sm" variant="outline" :disabled="i===form.sections.length-1" aria-label="Move section later" @click="move(i,1)">↓</Button><Button type="button" size="sm" variant="outline" @click="form.sections.splice(i,1)">Remove section</Button></div></div><div class="grid gap-3 sm:grid-cols-2"><Field v-model="section.type" label="Section type" type="select" :options="options(['hero','service','gallery','featured','process','values','statistics','consultation','contact'])"/><Field v-model="section.title" label="Heading"/><Field v-model="section.value" label="Statistic or short value (optional)"/><Field v-model="section.media_uuid" label="Section image" type="select" :options="[{value:'',label:'No image'},...images.map((m:any)=>({value:m.uuid,label:m.title||m.role+' image'}))]"/></div><Field v-model="section.text" label="Text" type="textarea"/><div class="grid gap-3 sm:grid-cols-2"><Field v-model="section.cta_label" label="Button / link label"/><Field v-model="section.cta_url" label="Button / link URL"/><Field v-model="section.reference_type" label="Featured content type" type="select" :options="[{value:'',label:'None'},...options(['trip','destination','rental_offer'])]" @update:model-value="section.reference_uuid=null"/><Field v-if="section.reference_type" v-model="section.reference_uuid" label="Featured content" type="select" :options="referenceOptions(section.reference_type)"/></div><LocalizedFields v-model="section.translations" :fields="['title','text','cta_label']"/></div><Button type="button" variant="outline" @click="addSection">Add section</Button></section>
<Field v-model="form.is_published" label="Published" type="checkbox"/><Button type="submit" :disabled="busy">{{busy?'Saving…':'Save page'}}</Button></fieldset></form><LibraryMedia v-if="form?.uuid" type="pages" :uuid="form.uuid" :images="images" :disabled="busy" @saved="load"/><p v-else class="text-sm text-muted-foreground">Save the page first, then add photos and select images for its sections.</p></DialogContent></Dialog>
</div></MainLayout></template>
