<script setup lang="ts">
import {ref,watch} from 'vue'
import Field from '@/components/services/ServiceField.vue'
import {Button} from '@/components/ui/button'
import api,{errorMessage} from '@/axiosClient'
const props=defineProps<{planner:any}>(),emit=defineEmits(['saved','dirty']),days=ref<any[]>([]),busy=ref(false),error=ref(''),dirty=ref(false)
watch(()=>props.planner,value=>{days.value=JSON.parse(JSON.stringify(value.seedRows));dirty.value=false},{immediate:true})
watch(dirty,value=>emit('dirty',value),{flush:'sync'})
function add(){days.value.push({day_number:days.value.length+1,title:'',destination_id:'',accommodation_name:'',accommodation_notes:'',stay_type:'',nights:0,breakfast:false,lunch:false,dinner:false,description:'',activity_lines:''});dirty.value=true}
function move(i:number,d:number){[days.value[i],days.value[i+d]]=[days.value[i+d],days.value[i]];dirty.value=true}
async function save(){busy.value=true;error.value='';try{await api.put('/trips/'+props.planner.trip.uuid+'/planner',{days:days.value.map((day,i)=>({...day,day_number:i+1}))},{headers:{'X-Safari-Workspace':'1'}});dirty.value=false;emit('saved')}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
</script>
<template><section class="space-y-4 rounded-xl border bg-card p-5 text-card-foreground"><h3 class="font-semibold">Trip itinerary</h3><p v-if="error" role="alert" class="text-destructive">{{error}}</p><p class="text-sm text-muted-foreground">{{dirty?'Unsaved itinerary changes':'Days and activities used when preparing quotations from this trip.'}}</p><form class="space-y-4" @submit.prevent="save" @input="dirty=true" @change="dirty=true"><article v-for="(day,i) in days" :key="i" class="space-y-4 rounded border p-4"><div class="flex flex-wrap justify-between gap-2"><h4 class="font-medium">Day {{i+1}}</h4><div class="flex gap-1"><Button type="button" variant="outline" size="sm" :disabled="busy||i===0" @click="move(i,-1)">Up</Button><Button type="button" variant="outline" size="sm" :disabled="busy||i===days.length-1" @click="move(i,1)">Down</Button><Button type="button" variant="outline" size="sm" :disabled="busy" @click="days.splice(i,1);dirty=true">Remove day</Button></div></div><div class="grid gap-3 sm:grid-cols-2"><Field v-model="day.title" label="Day title"/><Field v-model="day.destination_id" label="Destination" type="select" :options="[{value:'',label:'Not specified'},...planner.destinations.map((d:any)=>({value:d.id,label:d.name}))]"/><Field v-model="day.accommodation_name" label="Accommodation"/><Field v-model="day.stay_type" label="Stay type"/><Field v-model="day.nights" label="Nights" type="number" :min="0"/></div><div class="flex flex-wrap gap-5"><Field v-model="day.breakfast" label="Breakfast" type="checkbox"/><Field v-model="day.lunch" label="Lunch" type="checkbox"/><Field v-model="day.dinner" label="Dinner" type="checkbox"/></div><Field v-model="day.description" label="Day description" type="textarea"/><Field v-model="day.accommodation_notes" label="Accommodation notes" type="textarea"/><Field v-model="day.activity_lines" label="Activities (one per line)" type="textarea"/></article><div class="flex gap-2"><Button type="button" variant="outline" :disabled="busy" @click="add">Add itinerary day</Button><Button type="submit" :disabled="busy">{{busy?'Saving…':'Save itinerary'}}</Button></div></form></section></template>
